name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache Isabelle Heaps
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-Isabelle2020-${{ hashFiles('ROOT') }}
          # Heap path($ISABELLE_HEAPS)
          path: |
            - .heaps

      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3

      - name: Show heap cache dir
        run: ls -al .

      - name: Build sessions
        uses: pandaman64/isabelle-action@v1.1-test
        with:
          args: "build -b -d Simpl -D . -v"
          heapCacheDir: .heaps

      - name: Show heap cache dir
        run: ls -al .heaps .

      - name: Upload heaps
        uses: actions/upload-artifact@v2
        with:
          name: heaps
          path: .heaps