name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache Isabelle Heaps
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-Isabelle2020-${{ hashFiles('ROOT') }}
          # Heap path($ISABELLE_HEAPS)
          path: |
            - /root/.isabelle/Isabelle2020/heaps

      - name: Build sessions
        uses: pandaman64/isabelle-action@v1
        with:
          args: "build -d Simpl -D . -v"

      - name: Upload heaps
        uses: actions/upload-artifact@v2
        with:
          name: heaps
          path: /root/.isabelle/